### ISSUE TITLE
compile error with rust 1.7

### ISSUE THREAD

**Issue by hgz07** [Connicpu/mtproto-rs#1]
tl_macros/build.rs:10:29: 10:42 error: mismatched types:
 expected `&mut syntex::Registry`,
    found `&mut syntex::Registry`
(expected struct `syntex::Registry`,
    found a different struct `syntex::Registry`) [E0308]
tl_macros/build.rs:10     quasi_codegen::register(&mut registry);
                                                  ^~~~~~~~~~~~~
tl_macros/build.rs:10:29: 10:42 help: run `rustc --explain E0308` to see a detailed explanation
tl_macros/build.rs:10:29: 10:42 note: Perhaps two different versions of crate `syntex` are being used?
tl_macros/build.rs:10     quasi_codegen::register(&mut registry);
                                                  ^~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `tl_macros`.

**Comment by habnabit** [comment]
Did #5 fix this, perhaps?
