### ISSUE TITLE
Hey guy what about docs?

### ISSUE THREAD

**Issue by friktor** [Connicpu/mtproto-rs#2]
You wrote a pretty good library, but it does not have any documentation or examples of use. Do not you think that this is not correct?

**Comment by Connicpu** [comment]
Thanks, but this library is far from finished! I just have the types defined but there's still a fair bit I need to do with the RPC flow before it's ready to actually be used. I just need to find the time to actually do that :P

**Comment by friktor** [comment]
Ok, i wait this lib %)
